apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: seesharp
  janus-idp.io/tekton: seesharp
  backstage.io/kubernetes-id: seesharp
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: seesharp
resources:
- deployment.yaml
- route.yaml
- service.yaml
