apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: seesharp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: seesharp 
  name: seesharp
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: seesharp
    weight: 100 
