apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: seesharp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: seesharp 
  name: seesharp
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: seesharp 
